#!/usr/bin/env php
<?php

$songNumbers = [];

for ($i = 0; $i < 39; $i++)
{
    $songNumbers[] = $i;
}

shuffle($songNumbers);

echo 'songplaylist:';
$i = 0;

foreach ($songNumbers as $key => $songNumber)
{
    if (!($i % 8))
    {
        echo PHP_EOL . '                    !byte ';
        if (!($key == array_key_last($songNumbers))) echo $songNumber . ', ';
    }
    else
    {
        echo $songNumber;

        if (!(($i % 8) == 7) && !($key == array_key_last($songNumbers)))
        {
            echo ', ';
        }
    }
    $i++;
}

echo PHP_EOL;
