#!/usr/bin/env php
<?php

$filename = 'labels.asm';
$fileArray = @file($filename);

$sortedLines = [];

foreach ($fileArray as $line)
{
    $lineArray = explode("=", $line);

    foreach ($lineArray as $key => $value)
    {
        $newValueArray = explode(";", $value);
        $newValue = trim(str_replace('$', '', $newValueArray[0]));

        if ($key == array_key_last($lineArray))
        {
            $lineArray[$key] = hexdec($newValue);
        }
        else
        {
            $lineArray[$key] = $newValue;
        }
    }

    $sortedLines[$lineArray[1]] = $lineArray[0];
}

ksort($sortedLines);

foreach ($sortedLines as $address => $label)
{
    printf('$%04X: %s' . PHP_EOL, $address, $label);
}
